# Generated by Django 5.0.7 on 2024-07-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPriceOfCoin',
            fields=[
                ('coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('coin', models.CharField(max_length=100)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriggeredAlerts',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('coin_name', models.CharField(max_length=50)),
                ('target', models.DecimalField(decimal_places=10, max_digits=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.targetpriceofcoin')),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.triggeredalerts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
