# Generated by Django 5.0.7 on 2024-07-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetpriceofcoin',
            name='flag_trigger',
            field=models.BooleanField(default=False),
        ),
    ]
